import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { getMigrations } from "better-auth/db/migration";
import { Pool } from "pg";
import { createAuthOptions } from "../src/lib/auth-options";

const args = new Set(process.argv.slice(2));
const apply = args.has("--apply");
const print = args.has("--print");
const outIndex = process.argv.indexOf("--out");
const outputPath = outIndex >= 0 ? process.argv[outIndex + 1] : "";

function timestamp() {
  return new Date().toISOString().replace(/[-:.TZ]/g, "").slice(0, 14);
}

async function main() {
  const connectionString = process.env.DATABASE_URL;

  if (!connectionString) {
    throw new Error("DATABASE_URL is required to generate or apply PostgreSQL migrations.");
  }

  const pool = new Pool({ connectionString });

  try {
    const authOptions = createAuthOptions({ database: pool });
    const migrations = await getMigrations(authOptions);
    const changeCount = migrations.toBeCreated.length + migrations.toBeAdded.length;

    if (changeCount === 0) {
      console.log("Better Auth schema is already up to date.");
      return;
    }

    const sql = await migrations.compileMigrations();
    const targetPath = outputPath || join("migrations", `${timestamp()}_better_auth.sql`);
    const fileBody = [
      "-- Generated by npm run db:migration",
      "-- Review before applying in production.",
      "",
      sql.trim(),
      "",
    ].join("\n");

    if (print) {
      console.log(fileBody);
    }

    await mkdir(outputPath ? dirname(targetPath) : "migrations", { recursive: true }).catch(() => undefined);
    await writeFile(targetPath, fileBody);
    console.log(`Wrote ${targetPath}`);

    if (apply) {
      await migrations.runMigrations();
      console.log("Applied Better Auth migration to DATABASE_URL.");
    } else {
      console.log("Run npm run db:migration:apply after reviewing the SQL.");
    }
  } finally {
    await pool.end();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
